# Generated by Django 2.2.15 on 2020-08-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_date',
            new_name='created_time',
        ),
    ]
